import = ["/Users/nagaoka/.config/alacritty/themes/themes/kanagawa_dragon.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "0xProto"
style = "Bold"

[font.normal]
family = "0xProto"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux new -A -s default"]
program = "/bin/zsh"

[window]
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 5
y = 0
