[character]
success_symbol = "[\\(* '-'\\)b](bold green)"
error_symbol = "[\\(* '-'\\)p](bold red)"
vicmd_symbol = "[V\\( '_'\\)V](bold green)"

[cmd_duration]
min_time = 10
show_milliseconds = true
format = "took [$duration](bold yellow)"

[git_branch]
symbol = "🌱 "

[gcloud]
disabled = true

[time]
disabled = false
format = "[| $time |](yellow) "
time_format = "%T"
utc_time_offset = "+9"
