- name: Deploy dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}"
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .aliases
    - .bashrc
    - .functions
    - .gdbinit
    - .starship.toml
    - .tmux.conf
    - .vimrc
    - .zshenv
    - .zshrc

- name: Create .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Deploy dotfiles in .config
  file:
    src: "{{ ansible_env.PWD }}/roles/dotfiles/files/.config/{{ item }}"
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
    force: yes
  loop:
    - alacritty
    - nvim
    - git
