env:
  TERM: xterm-256color
window:
  padding:
    x: 5
    y: 0
  opacity: 0.9
font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular
  bold:
    family: "Hack Nerd Font Mono"
    style: Bold
  size: 13
