env:
  TERM: xterm-256color
window:
  padding:
    x: 5
    y: 0
  opacity: 0.9
  startup_mode: Maximized
font:
  normal:
    family: "Hack Nerd Font"
    style: Regular
  bold:
    family: "Hack Nerd Font"
    style: Bold
  size: 13
shell:
  program: /bin/zsh
  args:
   - -l
   - -c
   - 'tmux new -A -s default'
