- name: Register the current docker version (if any)
  command: docker --version
  register: docker_version_check
  ignore_errors: yes
  changed_when: false

- block:
  - name: Remove the current docker
    apt:
      pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
      purge: yes
    become: yes
  
  - name: Install packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common
    become: yes

  - name: Add key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
    become: yes

  - name: Add apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    become: yes

  - name: Install docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
    become: yes

  when: docker_version_check is failed

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.3.0/docker-compose-linux-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: yes
